/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Frames;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Haji Khokar
 */
public class CopyPaste extends javax.swing.JFrame {
FileInputStream fin=null;
 FileOutputStream fout=null;
 int packedSize=100;
int size;
int totakPacked;
int LastPackedSized;
// String path;
 /**
     * Creates new form CopyPaste
     */
    public CopyPaste() {
        initComponents();
    }
    File f;
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        packetsizeTextField1 = new javax.swing.JTextField();
        destinationTextField2 = new javax.swing.JTextField();
        jfilesizeTextField3 = new javax.swing.JTextField();
        totalpackets = new javax.swing.JTextField();
        lastpacketsizeTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        filenameTextField6 = new javax.swing.JTextField();
        originTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tranfer = new javax.swing.JButton();
        pro = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(packetsizeTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 250, 30));
        getContentPane().add(destinationTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 156, 223, 27));

        jfilesizeTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfilesizeTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jfilesizeTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 250, 30));
        getContentPane().add(totalpackets, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 250, 30));
        getContentPane().add(lastpacketsizeTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 250, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FILE NAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("FILE SIZE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 274, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("PACKET SIZE");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 329, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("TOTAL PACKETS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 378, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("LAST PACKET SIZE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("ENTER ORIGIN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 38, 178, 26));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("ENTER DESTINATION ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 123, -1, -1));
        getContentPane().add(filenameTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 250, 30));
        getContentPane().add(originTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 80, 218, 27));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("BROWSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 78, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Destination");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 151, -1, -1));

        tranfer.setText("transfer");
        tranfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tranferActionPerformed(evt);
            }
        });
        getContentPane().add(tranfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));
        getContentPane().add(pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 464, 390, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfilesizeTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfilesizeTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfilesizeTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       JFileChooser chooser=new JFileChooser();
chooser.showDialog(this,"open");
       String pasteFile = ""+chooser.getSelectedFile();
       try
       {
           fout =new FileOutputStream(""+pasteFile);
           destinationTextField2.setText(pasteFile);
       } catch (FileNotFoundException ex) {
        Logger.getLogger(CopyPaste.class.getName()).log(Level.SEVERE, null, ex);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser= new JFileChooser();
        chooser.showDialog(this, "open");
        String path1=""+ chooser.getSelectedFile();
        f=chooser.getSelectedFile();
        originTextField7.setText(path1);
    
        try {
            fin=new FileInputStream(""+f);
        originTextField7.setText(path1);
 
        size=fin.available();
         } catch (FileNotFoundException ex) {
            Logger.getLogger(CopyPaste.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
        Logger.getLogger(CopyPaste.class.getName()).log(Level.SEVERE, null, ex);
    }
        totakPacked= size/packedSize;
        LastPackedSized= size%packedSize;
        filenameTextField6.setText(chooser.getSelectedFile().getName());
        jfilesizeTextField3.setText(""+size);
        packetsizeTextField1.setText(""+packedSize);
        totalpackets.setText(""+totakPacked);
        lastpacketsizeTextField5.setText(""+LastPackedSized);
    

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tranferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tranferActionPerformed

    TranferButton tf=new TranferButton();    
    tf.start();

        // TODO add your handling code here:
    }//GEN-LAST:event_tranferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CopyPaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CopyPaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CopyPaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CopyPaste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display th^e form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CopyPaste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField destinationTextField2;
    private javax.swing.JTextField filenameTextField6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jfilesizeTextField3;
    private javax.swing.JTextField lastpacketsizeTextField5;
    private javax.swing.JTextField originTextField7;
    private javax.swing.JTextField packetsizeTextField1;
    private javax.swing.JProgressBar pro;
    private javax.swing.JTextField totalpackets;
    private javax.swing.JButton tranfer;
    // End of variables declaration//GEN-END:variables

class TranferButton extends Thread
{
    public void run()
    {
        
        try{
            pro.setStringPainted(true);
            pro.setValue(0);
            pro.setMaximum(packedSize);
            pro.setMinimum(0);
            byte data[]=new byte[packedSize];
            int i=0;
            while(i<=packedSize)
            {
                pro.setValue(i+10);
                fin.read(data,0,packedSize);
                fout.write(data,0,packedSize);
                Thread.sleep(100);
            i++;
            }
            fin.read(data,0,LastPackedSized);
            fout.write(data,0,LastPackedSized);
            pro.setValue(0);
           JOptionPane.showMessageDialog(null,"SUCCESSFULLY TRANSFERED");
        }catch(Exception ex)
        {
            ex.printStackTrace();
        }
        try{
        fin.read();
        fout.close();
        }catch(Exception ee){ee.printStackTrace();}
    }
}

}